#! /usr/bin/env ruby
# because rubygems shims assume a gem's executables are Ruby

require "litestream/commands"

begin
  command = [Litestream::Commands.executable, *ARGV]
  exec(*command)
rescue Litestream::Commands::UnsupportedPlatformException, Litestream::Commands::ExecutableNotFoundException => e
  warn("ERROR: " + e.message)
  exit 1
end
